// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "space":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffff5fffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff5fffffffffffffffffffffffffffff5ffffffffffffffffffffff5ffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff5fffffffffffffffffffffffffffff5fffffffffffffffffffffff5fffffffffffff55ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff5fffffffffffffffffffffffffffff5ffffffffffffffffffffffff5fffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff5fffffffffffffffffffffffffffff5fffffffffffffffffffffffff5ffffffff55fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffff5ffffffffffffffffffffffffffffff5ffffffffffffffffffffffffff55fffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffff55ffff5ffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffff5ff55fffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffff5fffffffffffffffffffffff
fffffff555f5fffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffff55fffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffff5fffffffffffffffffffffff
ffffffffff55ffffffffffffff5ffffffffffffff5ffffffffffffffffffffffffffffff55ffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffff5fffffffffffffffffffffff
fffffffffff5555555fffffffff555fffffffffff5ffffffffffffffffffffffffffff55ff5fffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffff5fffffffffffffffffffffff
fffffffffff5ffffff55555555ffff555ffffffff5fffffffffffffffffffffffffff5fffff55ffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffff5fffffffffffffffffffffff
fffffffffff5fffffffffffffffffffff55ffffff5ffffffffffffffffffffffffff5ffffffff55fffffffffffffffffffffffff5fffffffffffffffffffffffffffffff5fffffffffffffffffffffff
fffffffffff5fffffffffffffffffffffff55555f5ffffffffffffffffffffffff55fffffffffff5ffffffffffffffffffffffff5ffffffffffffffffff5ffffffffffff5fffffffffffffffffffffff
ffffffffff5fffffffffffffffffffffffffffff555ffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffff5fffffffffffffffff5ffffffffffff5fffffffffffffffffffffff
fffffffff5fffffffffffffffffffffffffffffff5555fffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffff5ffffffffffffffff5fffffffffffff5fffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff5fff5555fffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffff5ffffffffffffff5fffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff5fffffff5555ffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffff5ffffffffffffff5fffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff5fffffffffff55ffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffff5fffffffffffffff5fffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff5fffffffffffff555ffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffff5ff5fffffffffffff5fffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffff5ffff555555555555555555555ffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff55ffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffff5fffffff5fffffffffffffffff5ffffffff555fffffffffffff
fffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffff5ffff55ffffffffffffffffff5ffffffffffffffffffffffff
ffffffffffffffffffffffffff5ffffffffffffff5ffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffff5f55ffffffffffffffffffff5ffffffffffffffffffffffff
fffffffffffffffff5ffffffff5fffffffffffff5ffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffff5ffffffffffffffffffffff5ffffffffffffffffffffffff
ffffffffffffffffff55ffffff5fffffffffffff5ffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffff55f5ffffffffffffffffffff5fffffffffffffffffffffffff
ffffffffffffffffffff5fffff5fffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffff55ffff55ffffffffffffffffff5fffffffffffffffffffffffff
fffffffffffffffffffff55fff5ffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffff5ffffffff5fffffffffffffffff5fffffffffffffffffffffffff
fffffffffffffffffffffff555fffffffffffffffffffffffffffffffffff5fffffffffffff5ffffffffffffffffffffffffffffff5ffffffffff5ffffffffffffffff5fffffffffffffffffffffffff
fffffffffffffffffffffffff55fffffffffffffffffffffffffffffffffff555ffffffffff5fffffffffffffffffffffffffffff5ffffffffffff5fffffffffffffff5fffffffffffffffffffffffff
ffffffffffffffffffffffff5ff55ffffffffffffffffffffffffffffffffffff555fffffff5ffffffffffffffffffffffffffff5ffffffffffffff5fffffffffffff5ffffffffffffffffffffffffff
fffffffffffffffffffffff5fffff55fffffffffffffffffffffffffffffffffffff55ffff5ffffffffffffffffffffffffffff5ffffffffffffffff55ffffffffff5fffffffffffffffffffffffffff
fffffffffffffffffffffff5ffffff55ffffffffffffffffffffffffffffffffffffff5555ffffffffffffffffffffffffffff55ffffffffffffffffff5fffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffff555ffffffffffffffffffffffffff5ffffffffffffffffffff5ffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffff5fff5555ffffffffffffffffffffffffffffffffffffffffffff55ffffffffffffffffffffffffffffffffff
ffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffff5fffffff5555ffffffffffffffffffffffffffffffffffffffffff55ffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffff55ffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffff5fffffffff5fffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffff5fffffffff5fffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffff5fffffff5fffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff5ffffff5fffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffff5ffff5fffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff55f5ffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffff55ffffffffffffffffffffffffffff5ffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff5ff55ffffffffffffffffffffffffff5fffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff5ffff5ffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff5ffffff55fffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff5ffffff55ffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffff5fffffffffffffff5fffffffffff55fffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff5ffffffffffffffff55fffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffff55ffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffff5fffffffffffffffffff5fffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffff5ffffffffffffffffffff5fffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff55ffffff5ffffffffffffffffffffffff5fffffffffffffffffffffffffffffff
ffffffff5ffffffffffffffffffffff5ffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff55fff5fffffffffffffffffffffffff5fffffffffffffffffffffffffffffff
ffffffff5fffffffffffffffffffffff5fff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5555ffffffffffffffffffffffffff5ffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffff555ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff555fffffffffffffffffffffffff5fffffffffff5fffffffffffffffff
fffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ff55ffffffffffffffffffffffff5fffffffff5ffffffffffffffffff
ffffffffffffffffffffffffffffffffff5f5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffff555555fffffffffffffffffff5ffffffff5ffffffffffffffffff
fffffffffffffffffffffffffffffffff5ff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffff555ffffffffffffffff5fffffff5fffffffffffffffffff
fffffffffffffffffffffffffffffffff5fff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffff5fffff5ffffffffffffffffffff
ffffffffffffffffffffffffffffffff5fffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffff5fff5fffffffffffffffffffff
fffffffffffffffffffffffffffffff5fffffff55fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffff5f5ffffffffffffffffffffff
ffffffffffffffffffffffffffffff5ffffffffff55ffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffff
ffffffffffffffffffffffffffffff5ffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffff555fffffffffffffffffffff
fffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffff5fff5ffffffffffffffffffff
ffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffff5fffff5fffffffffffffffffff
ffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffff5fffffff55fffffffffffffffff
fffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffff55fffffffffffffffffffffffffff
fffffffffffffffffffffffff55fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff55ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff55f5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff5fffffffffffffffffffffffffffffff5fffffffffffffff5fffffffffffffffffffffffff5fffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff5ffffffffffffffffffffffffffffffff55fffffffffffff5ffffffffffffffffffffffffff5fffffffffffff55ffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff5ffffffffffffffffffffffffffffffffff5fffffffffff5ffffffffffffffffffffffffffff5ffffffffffff5fffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff5fffffffffffffffffffffffffffffffffff55ffffffff5ffffffffffffffffffffffffffffff5ffffffffff5ffffffffffffff5ffffffffffffff5fffffffffffffffffffffffffffffff
ffffffffff5fffffffffffffffffffffffffffffffffffff5ffffff5fffffffffffffffffffffffffffffff5ffffffff55ffffffffffffffff5fffffffffff55ffffffffffffffffffffffffffffffff
ffffffffff5ffffffffffffffffffffffffffffffffffffff55ffff5ffffffffffffffffffffffffffffffff5fffff55ffffffffffffffffff5fffffff5555ffffffffffffffffffffffffffffffffff
fffffffffff5fffffffffffffffffffffffffffffffffffffff55f5ffffffffffffffffffffffffffffffffff5ff55fffffffffffffffffffff5f55555ffffffffffffffffffffffffffffffffffffff
fffffffffff55555555555555ffffffffffffffffffffffffffff55ffffffffffffffffffffffffffffffffff5f5ffffffffffffffffffffff555fffffffffffffffffffffffffffffffffffffffffff
fffff5555555ffffffffffffffffffffffffffffffffffffffff5ff55ffffffffffffffffffffffffffffffff55fffffffffffffffffffff55ff5fffffffffffffffffffffffffffffffffffffffffff
fffffffffff5fffffffffffffffffffffffffffffffffffffff5fffff55ffffffffffffffffffffffffffff55ff5ffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffff
fffffffffff5fffffffffffffffffffffffffffffffffffffff5fffffff555ffffffffffffffffffffffff5ffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffff5ffffffffffffffffffffffffffffffffffffff5fffffffffff5555fffffffffffffffffff5ffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffff555fffffffffffffff5ffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffff5ffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
            case "image4":return img`
....2.............2....
2...2.............2...2
2...2.............2...2
2...2.............2...2
2...2.............2...2
2.....................2
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
.......................
`;
            case "image3":return img`
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
...........7.....7...........
............7...7............
...........7777777...........
..........77.777.77..........
.........77777777777.........
.........7.7777777.7.........
.........7.7.....7.7.........
............77.77............
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
.............................
`;
            case "image2":
            case "Blaster Ship":return img`
...................f...................
..................faf..................
.................faaaf.................
.................facaf.................
................faacaaf................
................facccaf................
...............faacccaaf...............
..............faacbbbcaaf..............
..............facb666bcaf..............
..............fab66666baf..............
..............fab66696baf..............
............a.fab66669baf.a............
........a...a.fab66669baf.a...a........
........a...c.fab66666baf.c...a........
........c...c.facb669bcaf.c...c........
........c..fcfacccbbbcccafcf..c........
........cffaaacccccccccccaaaffc........
......ffaaacccccccccccccccccaaaff......
....ffaaccccccccbabcbabccccccccaaff....
..ffaaccccccccccabacabaccccccccccaaff..
.faacccccccaacccbabababcccaacccccccaaf.
faccccccaaaffaccccabaccccaffaaaccccccaf
faccaaaafff..facbabababcaf..fffaaaaccaf
.faaffff.....facabacabacaf.....ffffaaf.
..ff.........facbabcbabcaf.........ff..
.............facccccccccaf.............
.............faccccfccccaf.............
.............facccfafcccaf.............
............faccccfafccccaf............
...........facccccfafcccccaf...........
..........faccccccfafccccccaf..........
.........facccccccfafcccccccaf.........
........facccccccafafacccccccaf........
.......facccccccafffffacccccccaf.......
......facccccccaff425ffacccccccaf......
......faaaaaaaaf.f524f.faaaaaaaaf......
.......ffffffff..f245f..ffffffff.......
.................f552f.................
.................42545.................
................4554525................
................5525554................
................5255452................
................5455555................
.................55255.................
.................55545.................
..................525..................
..................555..................
...................5...................
.......................................
`;
            case "image5":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . a . . . . . . . . 
. . . . . . . a . . . . . . . . 
. . . . . . . a . . . . . . . . 
. . . . . . . a . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
