namespace SpriteKind {
    export const laser = SpriteKind.create()
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    music.setVolume(45)
    music.pewPew.play()
    pause(170)
    projectile = sprites.createProjectileFromSprite(img`
        ....2.............2....
        2...2.............2...2
        2...2.............2...2
        2...2.............2...2
        2...2.............2...2
        2.....................2
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        .......................
        `, Blaster_Ship, 0, -100)
})
sprites.onDestroyed(SpriteKind.Player, function (sprite) {
    info.setScore(info.highScore())
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    projectile2 = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . a . . . . . . . . 
        . . . . . . . a . . . . . . . . 
        . . . . . . . a . . . . . . . . 
        . . . . . . . a . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, Aliens, 0, 100)
    info.changeScoreBy(5)
    pause(500)
})
let Aliens: Sprite = null
let projectile2: Sprite = null
let projectile: Sprite = null
let Blaster_Ship: Sprite = null
Blaster_Ship = sprites.create(assets.image`Blaster Ship`, SpriteKind.Player)
controller.moveSprite(Blaster_Ship, 60, 60)
Blaster_Ship.setStayInScreen(true)
Blaster_Ship.setPosition(79, 100)
scene.setBackgroundImage(assets.image`space`)
info.setLife(4)
game.onUpdateInterval(2000, function () {
    Aliens = sprites.create(img`
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        ...........7.....7...........
        ............7...7............
        ...........7777777...........
        ..........77.777.77..........
        .........77777777777.........
        .........7.7777777.7.........
        .........7.7.....7.7.........
        ............77.77............
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        .............................
        `, SpriteKind.Enemy)
    Aliens.setPosition(randint(5, 100), 16)
    Aliens.setBounceOnWall(true)
    Aliens.vx += 70
    Aliens.setFlag(SpriteFlag.AutoDestroy, true)
})
